### ISSUE TITLE
Q: how does this mod have a 1.19.3 version when one of its dependencies (ForgeConfigAPIPort) doesn't?

### ISSUE THREAD

**Issue by LastExceed** [AHilyard/ItemBorders#11]
is there a way to run it anyway?

**Comment by AHilyard** [comment]
Forge Config API Port has a 1.19.3 version.  You can find it here: https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric/files/4381441

**Comment by LastExceed** [comment]
oops, i got jebaited ![](https://i.imgur.com/3Datc4C.png)
