### ISSUE TITLE
1.21 ItemBorders/LegendaryToolTips/AdvancementPlaques crash

### ISSUE THREAD

**Issue by Ecthelion75** [AHilyard/ItemBorders#30]
Tested AdvancementPlaques-1.21-neoforge-1.6.3, ItemBorders-1.21-neoforge-1.2.4 and LegendaryTooltips-1.21-neoforge-1.4.8 with Iceberg-1.21-neoforge-1.2.1 and Prism-1.21-neoforge-1.0.8 on neoForge-21.0.144 with no other mods present. Received this error for all three mods:

"Name" has failed to load correctly.
java.lang.AbstractMethodError:Receiver class
com.anthonyhilyard.iceberg.neoforge.config.NeoForgeIcebergConfigSpec does not define or inherit an implementation of the resolved method 'abstract void validateSpec(net.neoforged.fml.config.ModConfig)' of interface net.neoforged.fml.config.IConfigSpec.

[crash-2024-07-29_19.55.37-fml.txt](https://github.com/user-attachments/files/16412270/crash-2024-07-29_19.55.37-fml.txt)

**Comment by AHilyard** [comment]
This is resolved with the latest version of Iceberg, enjoy! 😄
