### ISSUE TITLE
Minecraft 1.12.2 Support of this mod

### ISSUE THREAD

**Issue by Titoo8899** [AHilyard/ItemBorders#5]
Hi,
I love it your mods are so good and I love so what. But I hope you can this Mod "ItemBorders" in the future make with a 1.12.2 Support why I search for this for a Project what I build.

**Comment by AHilyard** [comment]
I'm very late to the party, but there is a 1.12.2 version available now: https://legacy.curseforge.com/minecraft/mc-mods/item-borders/files/4590380
